delete cpp_mexapi_version.o ...
    mcauchy_get_reinitialization_statistics.mexmaca64 mcauchy_get_reinitialization_statistics.o ...
    mcauchy_get_marginal_2D_pointwise_cpdf.mexmaca64 mcauchy_get_marginal_2D_pointwise_cpdf.o ...
    mcauchy_get_marginal_1D_pointwise_cpdf.mexmaca64 mcauchy_get_marginal_1D_pointwise_cpdf.o ...
    mcauchy_initialize_lti.mexmaca64 mcauchy_initialize_lti.o ...
    mcauchy_set_window_number.mexmaca64 mcauchy_set_window_number.o ...
    mcauchy_reset.mexmaca64 mcauchy_reset.o ...
    mcauchy_set_master_step.mexmaca64 mcauchy_set_master_step.o ...
    mcauchy_shutdown.mexmaca64 mcauchy_shutdown.o ...
    mcauchy_step.mexmaca64 mcauchy_step.o

% Allow lldb to watch for memory leaks
setenv('CFLAGS', '-fno-omit-frame-pointer -fsanitize=address');
setenv('LDFLAGS', '-fsanitize=protect-initialized-data -fsanitize=leak -fsanitize=address');

% The following two lines are specific to Nishad's computer. Please change
% depending on your own locations
includePath = '-I/Users/nishadelias/Documents/GitHub/CauchyFriendly/scripts/swig/cauchy -I/opt/homebrew/opt/lapack/include';
libraryPath = '-L/opt/homebrew/opt/lapack/lib -llapacke -llapack -lblas -lm -lpthread';

eval(['mex -g ', includePath, ' ', libraryPath, ' matlab_wrapped/mcauchy_initialize_lti.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' matlab_wrapped/mcauchy_step.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' matlab_wrapped/mcauchy_shutdown.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' matlab_wrapped/mcauchy_set_window_number.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' matlab_wrapped/mcauchy_reset.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' matlab_wrapped/mcauchy_set_master_step.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' matlab_wrapped/mcauchy_get_reinitialization_statistics.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' matlab_wrapped/mcauchy_get_marginal_2D_pointwise_cpdf.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' matlab_wrapped/mcauchy_get_marginal_1D_pointwise_cpdf.cpp']);
