mex -setup c++
delete cpp_mexapi_version.o ...
    mcauchy_free_names.mexa64 mcauchy_free_names.o ...
    mcauchy_get_reinitialization_statistics.mexa64 mcauchy_get_reinitialization_statistics.o ...
    mcauchy_get_marginal_2D_pointwise_cpdf.mexa64 mcauchy_get_marginal_2D_pointwise_cpdf.o ...
    mcauchy_get_marginal_1D_pointwise_cpdf.mexa64 mcauchy_get_marginal_1D_pointwise_cpdf.o ...
    mcauchy_get_nonlin_function_pointers.mexa64 mcauchy_get_nonlin_function_pointers.o...
    mcauchy_initialize_lti.mexa64 mcauchy_initialize_lti.o ...
    mcauchy_initialize_nonlin.mexa64 mcauchy_initialize_nonlin.o ...
    mcauchy_reset.mexa64 mcauchy_reset.o ...
    mcauchy_set_window_number.mexa64 mcauchy_set_window_number.o ...
    mcauchy_set_master_step.mexa64 mcauchy_set_master_step.o ...
    mcauchy_shutdown.mexa64 mcauchy_shutdown.o ...
    mcauchy_single_step_nonlin.mexa64 mcauchy_single_step_nonlin.o ...
    mcauchy_step.mexa64 mcauchy_step.o
delete mcauchy_dynamics_get_n.mexa64 mcauchy_dynamics_get_n.o ...
    mcauchy_dynamics_get_pncc.mexa64 mcauchy_dynamics_get_pncc.o ...
    mcauchy_dynamics_get_cmcc.mexa64 mcauchy_dynamics_get_cmcc.o ...
    mcauchy_dynamics_get_p.mexa64 mcauchy_dynamics_get_p.o ...
    mcauchy_dynamics_get_step.mexa64 mcauchy_dynamics_get_step.o ...
    mcauchy_dynamics_get_dt.mexa64 mcauchy_dynamics_get_dt.o ...
    mcauchy_dynamics_get_x.mexa64 mcauchy_dynamics_get_x.o ...
    mcauchy_dynamics_set_x.mexa64 mcauchy_dynamics_set_x.o ...
    mcauchy_dynamics_get_u.mexa64 mcauchy_dynamics_get_u.o ...
    mcauchy_dynamics_get_Phi.mexa64 mcauchy_dynamics_get_Phi.o ...
    mcauchy_dynamics_set_Phi.mexa64 mcauchy_dynamics_set_Phi.o ...
    mcauchy_dynamics_get_Gam.mexa64 mcauchy_dynamics_get_Gam.o ...
    mcauchy_dynamics_set_Gam.mexa64 mcauchy_dynamics_set_Gam.o ...
    mcauchy_dynamics_get_B.mexa64 mcauchy_dynamics_get_B.o ...
    mcauchy_dynamics_set_B.mexa64 mcauchy_dynamics_set_B.o ...
    mcauchy_dynamics_set_beta.mexa64 mcauchy_dynamics_set_beta.o ...
    mcauchy_dynamics_get_H.mexa64 mcauchy_dynamics_get_H.o ...
    mcauchy_dynamics_set_H.mexa64 mcauchy_dynamics_set_H.o ...
    mcauchy_dynamics_get_gamma.mexa64 mcauchy_dynamics_get_gamma.o ...
    mcauchy_dynamics_set_gamma.mexa64 mcauchy_dynamics_set_gamma.o ...
    mcauchy_dynamics_set_is_xbar_set_for_ece.mexa64 mcauchy_dynamics_set_is_xbar_set_for_ece.o...
    mcauchy_dynamics_set_zbar.mexa64 mcauchy_dynamics_set_zbar.o


% Allow lldb to watch for memory leaks
setenv('CFLAGS', '-fno-omit-frame-pointer -fsanitize=address');
setenv('LDFLAGS', '-fsanitize=protect-initialized-data -fsanitize=leak -fsanitize=address');

% The following two lines are specific to Nishad's computer. Please change depending on your own locations
includePath = '-I/home/natsubuntu/Desktop/SysControl/estimation/CauchyCPU/CauchyEst_Nat/CauchyFriendly/scripts/swig/cauchy -I/home/natsubuntu/Desktop/SysControl/estimation/CauchyCPU/CauchyEst_Nat/CauchyFriendly/include';
libraryPath = '-lm -lpthread';


eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_initialize_lti.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_step.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_shutdown.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_set_window_number.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_reset.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_set_master_step.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_get_reinitialization_statistics.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_get_marginal_2D_pointwise_cpdf.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_get_marginal_1D_pointwise_cpdf.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_get_nonlin_function_pointers.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_initialize_nonlin.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_single_step_nonlin.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_free_names.cpp']);



eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_get_n.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_get_pncc.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_get_cmcc.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_get_p.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_get_step.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_get_dt.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_get_x.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_set_x.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_get_u.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_get_Phi.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_set_Phi.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_get_Gam.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_set_Gam.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_get_B.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_set_B.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_set_beta.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_get_H.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_set_H.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_get_gamma.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_set_gamma.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_set_is_xbar_set_for_ece.cpp']);
eval(['mex -g ', includePath, ' ', libraryPath, ' ../matlab_wrapped/mcauchy_dynamics_set_zbar.cpp']);


